CCTV_TYPE: robot_cctv
SCREEN_WIDTH: 1280
SCREEN_HEIGHT: 720

# SERVER_URL: http://router.softonnet.com:33101
SERVER_URL: "http://172.29.169.44:5000"

POST_REGISTER_API: /api/videoays/register_cctv
POST_UNREGISTER_API: /api/videoays/unregister_cctv
POST_EVENT_RESULT_API: /api/videoays/get_event_result