MODE: quarantine

SERVICE_RUNTIME: 5
TIME_OFFSET_PREV: -5
TIME_OFFSET_NEXT: 5

TEMPERATURE_LIMIT: 37.5
MASK_LIMIT: 4
DISTANCE_LIMIT: 3

SPEED_FIRST_POI: 0.5
SPEED_REST_POI: 0.2

DISABLE_GLOBAL_PATH_PLANNING: false
DISABLE_OBSTACLE_AVOIDANCE_FIRST_POI: true
DISABLE_OBSTACLE_AVOIDANCE_REST_POI: true

TRY_LPT_COUNT: 5
TRY_DRIVE_COUNT: 5

USE_INTERNAL_TEMPERATURE_ANALYSIS: True
USE_INTERNAL_MASK_ANALYSIS: True
USE_EXTERNAL_MASK_ANALYSIS: False
USE_INTERNAL_DISTANCE_ANALYSIS: True
USE_EXTERNAL_DISTANCE_ANALYSIS: False