MODE: quarantine

SERVICE_RUNTIME: 5
TIME_OFFSET_PREV: -5
TIME_OFFSET_NEXT: 5

TEMPERATURE_HIGH: 37.5
NOMASK_DISTANCE_LIMIT: 4
SOCIAL_DISTANCING_DISTANCE_LIMIT: 3

SPEED_FIRST_POI: 0.5
SPEED_REST_POI: 0.2

DISABLE_GLOBAL_PATH_PLANNING: false
DISABLE_OBSTACLE_AVOIDANCE_FIRST_POI: true
DISABLE_OBSTACLE_AVOIDANCE_REST_POI: true

TRY_LPT_COUNT: 5
TRY_DRIVE_COUNT: 5