- name: "W_102"
  poi:
    - pose:
        x: 806.9146346803717
        y: 415.44293581039193
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.5
        w: -0.866
      lpt:
        lift: 300
        pan: 0
        tilt: 0
    - pose:
        x: -18.9477864505
        y: 1.71135316756
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0475016233773
        w: -0.998871160749
      lpt:
        lift: 300
        pan: 0
        tilt: 0
- name: "W_103"
  poi:
    - pose:
        x: 864.4376042292665
        y: 535.10005446214
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.259
        w: -0.966
      lpt:
        lift: 300
        pan: 0
        tilt: 0