locations:
  - name: "W_101"
    poi:
      - pose:
          x: 678.509222626
          y: 380.371027296
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.999252314688
          w: -0.0386627933573
        lpt:
          lift: 100
          pan: 0
          tilt: 0
      - pose:
          x: 672.808363697
          y: 379.903865883
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0346401566639
          w: 0.999399849683
        lpt:
          lift: 100
          pan: 0
          tilt: 0
  - name: "W_102"
    poi:
      - pose:
          x: 678.509222626
          y: 380.371027296
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.999252314688
          w: -0.0386627933573
        lpt:
          lift: 100
          pan: 0
          tilt: 0
      - pose:
          x: 672.808363697
          y: 379.903865883
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0346401566639
          w: 0.999399849683
        lpt:
          lift: 100
          pan: 0
          tilt: 0
  - name: "W_103"
    poi:
      - pose:
          x: 678.509222626
          y: 380.371027296
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.999252314688
          w: -0.0386627933573
        lpt:
          lift: 100
          pan: 0
          tilt: 0
      - pose:
          x: 672.808363697
          y: 379.903865883
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: 0.0346401566639
          w: 0.999399849683
        lpt:
          lift: 100
          pan: 0
          tilt: 0
  - name: "E_101"
    poi:
      - pose:
          x: 304.52
          y: 380.15
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: -0.11
          w: 0.99
        lpt:
          lift: 100
          pan: 0
          tilt: 0
      - pose:
          x: 313.71
          y: 379.28
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: -0.07
          w: 1.0
        lpt:
          lift: 100
          pan: 0
          tilt: 0
  - name: "E_102"
    poi:
      - pose:
          x: 304.52
          y: 380.15
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: -0.11
          w: 0.99
        lpt:
          lift: 100
          pan: 0
          tilt: 0
      - pose:
          x: 313.71
          y: 379.28
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: -0.07
          w: 1.0
        lpt:
          lift: 100
          pan: 0
          tilt: 0
  - name: "E_103"
    poi:
      - pose:
          x: 304.52
          y: 380.15
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: -0.11
          w: 0.99
        lpt:
          lift: 100
          pan: 0
          tilt: 0
      - pose:
          x: 313.71
          y: 379.28
          z: 0.0
        orientation:
          x: 0.0
          y: 0.0
          z: -0.07
          w: 1.0
        lpt:
          lift: 100
          pan: 0
          tilt: 0