ROBOT_ID: SeRo01
ROBOT_TERMINAL: P03
ROBOT_ZONE: "1"
ROBOT_SORT: "1"
ROBOT_MODE: "1"
ROBOT_DESC: inspection_robot

USE_OVERTEMPERATURE: True
USE_DISTANCE_ANALYSIS: False
USE_MASK_ANALYSIS: False
USE_INTERNAL_DISTANCE_ANALYSIS: False
USE_INTERNAL_MASK_ANALYSIS: True